### PR TITLE
increase ring size by 1

### PR DESCRIPTION
**Pull request by nwadams**
@carolineleung @elihart

### CODE REVIEW

**Comment by carolineleung** [comment]
What is the reasoning behind bumping it up by 1?

**Comment by nwadams** [comment]
increasing sample size should reduce random variances affecting the mode. at the cost of slower response time. (of changing modes)

**Comment by geo-opensource** [comment]
+1

**Comment by carolineleung** [comment]
:+1: Good to include that as a doc/comment for `RING_SIZE`

**Pull request merged**
