### PR TITLE
increase low bandwidth triggers

### PR DESCRIPTION
**Pull request by nwadams**

### CODE REVIEW

**Comment by petzel** [comment]
LGTM

**Comment by elihart** [comment]
`BANDWIDTH_HYSTERETIC_LOWER` seems very low now, wouldn't we still want low bandwidth mode if the user had 30 kB/s? Maybe instead of changing the lower hysteretic we could just change the high one so that users can get out of low bandwidth mode easier, or increase the ring size so that image load speed is averaged out more and network blips won't affect it as much

**Comment by nwadams** [comment]
well I think the low is too high. We are still getting into low bandwidth on our lte devices? So obviously something is not working.

**Comment by elihart** [comment]
I'm guessing it's because we're using a sample size of only 4. If there is a temporary network issue I could see our devices hitting a speed that low temporarily depending on the time frame you look at, but I'm sure on a longer time scale our average network speeds are much higher than 40 kB/s. 

If you actually have a sustained network speed of 40 kB/s you would probably want to be in low bandwidth mode.

**Pull request merged**
