### PR TITLE
fix synchronous image loader

### PR DESCRIPTION
**Pull request by nwadams**

### CODE REVIEW

**Comment by nwadams** [comment]
view with w=1

**Comment by lxdvs** [comment]
I'm slightly worried about a cache hit or something returning a validly null bitmap and the wait() holding forever. Whats your opinion on the risk there?

**Comment by nwadams** [comment]
the container has a null cache key and null image listener when it instantly returns. I'll see if I can check the cache key to validate against a validly null bitmap.

**Comment by lxdvs** [comment]
```
      _~  _~
   __|=|_|=|__
   \ o.o.o.oY/
    \_______/
```

**Pull request closed without merging**
