### PR TITLE
Stetho: Adds OkHttpStack and renames original one to OkHttpHurlStack

### PR DESCRIPTION
**Pull request by felipecsl**
- Fixes project directory structure (again)
- Adds `OkHttpStack` which uses OkHttp's own networking API, instead of `HttpURLConnection` API (which is used by `OkHttpHurlStack`. This is needed in order for `StethoInterceptor` to work properly

### CODE REVIEW

**Comment by nwadams** [comment]
can we do the structure in one PR. separate from the okhttp stack. . Also you shoudl get alex to add you as a contributor and then you can maek commits directly to the repo and make a PR.

**Comment by nwadams** [comment]
any adverse effects from using native okhtpt instead of okhttp-urlconnection for requests?

**Comment by felipecsl** [comment]
I can do in 2 PRs but that would be really painful now since I'd have to pretty much revert everything and start over. It doesnt change anything at all, other than using the default folder structure. If you're really concerned about that, then I can separate.

If there are subtle bugs in `OkHttpStack` that could cause problems, so I'd keep using `OkHttpHurlStack` for a while and only use `OkHttpStack` for debug builds, where you want to have Stetho turned on. If it works well you can make the switch later.

**Comment by nwadams** [comment]
okay. lets leave it as one PR then.

**Comment by felipecsl** [comment]
thanks :)

**Comment by felipecsl** [comment]
:ship: ?

**Comment by nwadams** [comment]
i'm merging this. feel free to make a phab to include this new submodule commit.

**Comment by felipecsl** [comment]
@nwadams ship it plz

**Comment by felipecsl** [comment]
thank you :+1:

**Pull request merged**
