### PR TITLE
[Proposal] Include whether a response came from the cache

### PR DESCRIPTION
**Pull request by elihart**
This would clean up logic around responses where we need to know whether the response we are getting is the network or cache version.

### CODE REVIEW

**Comment by petzel** [comment]
can you show an example of this usage? 

wouldn't we also have to change all of the `RequestListener.onResponse` instances?

**Comment by carolineleung** [comment]
I'm a bit confused as why we need this? There is already a `request.willMissCache()` that you can use to see if you'll get the cache or network response. Is that insufficient?

**Comment by elihart** [comment]
Instead of changing all the `Listener.onResponse` instances I just added a method to the request itself - https://phabricator.musta.ch/D3232

This isn't needed and we can accomplish the same thing with `willMissCache` but doing it that way is fairly convoluted. You can see how we currently do it in `fetchHostHome` in `HostHomeFragment`, whereas with this change we could do one line `request.isCachedResponse`.

This definitely isn't needed but it's cleaner in some ways and I thought I'd throw it out there for discussion.

**Comment by carolineleung** [comment]
Ah okay, so this is meant to replace `willMissCache` with a cleaner interface. I can be convinced to buy into that. Could you rewrite `HostHomeFragment.fetchHostHome` to use this new approach to illustrate the cleanup?

**Comment by elihart** [comment]
I updated https://phabricator.musta.ch/D3232 to show an example of how this cleans up logic. This doesn't necessarily replace `willMissCache` that is still useful if you want to know before hand if there will be a cache hit, like if you need to know whether or not to show a loader.

**Comment by elihart** [comment]
Going to close this for now. I don't think the added complexity and messiness actually helps much.

**Pull request closed without merging**
